Jdb 002 create project table
JTDs-Inc/db-project pull request #2
Opened 2024-09-26 15:25 UTC by james-liam-butler

2024-09-26 15:30 UTC, lukemKainos approved these changes

2024-09-26 15:38 UTC, lukemKainos commented on src/main/resources/db/migration/V2__create_project_table.sql
> +    `name` varchar(50),
Is this your primary key?

2024-09-26 15:45 UTC, james-liam-butler commented on src/main/resources/db/migration/V2__create_project_table.sql
> +    `name` varchar(50),
no, new primary key is projectId

2024-09-26 15:47 UTC, lukemKainos requested changes

2024-09-26 15:47 UTC, lukemKainos commented on src/main/resources/db/migration/V2__create_project_table.sql
> +    projectId int NOT NULL,
Are you going to add the ids manually?

2024-09-27 09:28 UTC, dana-kainos requested changes
salesEmployeeID should be camel case

2024-09-27 09:51 UTC, lukemKainos requested changes
Fix this pr title

2024-09-27 09:59 UTC, lukemKainos approved these changes

2024-09-27 10:08 UTC, dana-kainos approved these changes

2024-09-27 10:09 UTC, merged